"""Blender export placeholder.

Generates a Python script that can be run inside Blender to create
an armature from skeleton graph data. Does NOT require Blender to be installed
for generation — only for execution.
"""

import json
from pathlib import Path
from typing import List, Dict


_BLENDER_TEMPLATE = '''
"""Auto-generated by HyperBone — run inside Blender's Python console or as a script."""
import bpy
import json

DATA = {data_json}

def create_armature(name, nodes, edges):
    bpy.ops.object.armature_add(enter_editmode=True)
    armature = bpy.context.object
    armature.name = name
    arm = armature.data
    arm.name = name + "_data"

    # Remove default bone
    for b in arm.edit_bones:
        arm.edit_bones.remove(b)

    # Create bones from edges
    node_map = {{n["id"]: n for n in nodes}}
    for i, edge in enumerate(edges):
        parent_node = node_map.get(edge["parent"])
        child_node = node_map.get(edge["child"])
        if not parent_node or not child_node:
            continue

        bone = arm.edit_bones.new(f"bone_{{i:03d}}")
        # Use XY as XZ in Blender (Z-up), scale to reasonable size
        px, py = parent_node["xy"]
        cx, cy = child_node["xy"]
        scale = 0.01
        bone.head = (px * scale, 0, -py * scale)
        bone.tail = (cx * scale, 0, -cy * scale)

    bpy.ops.object.mode_set(mode='OBJECT')
    return armature

# Build armature for first frame
if DATA:
    first = DATA[0]
    create_armature(
        f"skeleton_frame_{{first['frame_idx']}}",
        first.get("nodes", []),
        first.get("edges", [])
    )
    print(f"[HyperBone] Created armature with {{len(first.get('edges', []))}} bones")
'''


def export_blender_script(
    records: List[Dict],
    output_dir: str,
    filename: str = "import_skeleton.py",
    max_frames: int = 100,
) -> Path:
    """Write a Blender-importable Python script from graph records."""
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    # Trim to max_frames
    data = records[:max_frames]

    # Serialize minimal data for the script
    minimal = []
    for rec in data:
        minimal.append({
            "frame_idx": rec.get("frame_idx", 0),
            "nodes": rec.get("nodes", []),
            "edges": rec.get("edges", []),
        })

    script = _BLENDER_TEMPLATE.replace("{data_json}", json.dumps(minimal, separators=(",", ":")))
    path = out / filename
    path.write_text(script, encoding="utf-8")
    return path
