"""Owned mapper validation report generator.

Produces summary.md with full pipeline statistics and the defensible claim.
"""

import numpy as np
from pathlib import Path
from typing import Dict, List
from collections import Counter


def generate_owned_mapper_report(stats: Dict, output_dir: str) -> Path:
    """Generate a validation report for the HyperBone-owned mapper run.

    Args:
        stats: Dict returned by run_proposal_skeleton.
        output_dir: Where to write summary.md.

    Returns:
        Path to the written report.
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / "summary.md"

    total = stats.get("accepted_count", 0) + stats.get("rejected_count", 0)
    acceptance_rate = stats["accepted_count"] / total * 100 if total > 0 else 0

    runtimes = stats.get("runtimes_ms", [])
    avg_runtime = float(np.mean(runtimes)) if runtimes else 0
    fastest = float(np.min(runtimes)) if runtimes else 0
    slowest = float(np.max(runtimes)) if runtimes else 0

    labels_accepted = Counter(stats.get("labels_accepted", []))
    labels_rejected = Counter(stats.get("labels_rejected", []))
    reason_counter = Counter(stats.get("reject_reasons", []))

    lines = [
        "# HyperBone Owned Mapper — Validation Report",
        "",
        "## Pipeline",
        "",
        "```",
        "DINO label+bbox (optional) → HyperBone crop → custom mask → custom thinning → custom graph → quality gate → export",
        "```",
        "",
        "## Run Configuration",
        "",
        f"| Parameter | Value |",
        f"|-----------|-------|",
        f"| Video | {stats.get('video_path', 'N/A')} |",
        f"| Resolution | {stats.get('resolution', 'N/A')} |",
        f"| Proposal source | {stats.get('proposal_source', 'N/A')} |",
        f"| Text prompt | {stats.get('text_prompt', 'N/A') or '(manual)'} |",
        f"| Skeleton mapper | hyperbone-custom |",
        f"| Mask backend | hyperbone-custom-mask |",
        f"| Graph builder | hyperbone-pixel-trace-v0 |",
        "",
        "## Results",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Frames processed | {stats.get('frames_processed', 0)} |",
        f"| Objects proposed | {stats.get('objects_proposed', 0)} |",
        f"| **Accepted graphs** | **{stats.get('accepted_count', 0)}** |",
        f"| Rejected graphs | {stats.get('rejected_count', 0)} |",
        f"| **Acceptance rate** | **{acceptance_rate:.1f}%** |",
        f"| Avg runtime/object | {avg_runtime:.1f} ms |",
        f"| Fastest object | {fastest:.1f} ms |",
        f"| Slowest object | {slowest:.1f} ms |",
        "",
    ]

    # Node/edge stats
    node_counts = stats.get("node_counts", [])
    edge_counts = stats.get("edge_counts", [])
    if node_counts:
        lines.extend([
            f"| Avg node count | {np.mean(node_counts):.1f} |",
            f"| Avg edge count | {np.mean(edge_counts):.1f} |",
            "",
        ])

    # Top labels accepted
    if labels_accepted:
        lines.extend([
            "## Top Labels — Accepted",
            "",
            "| Label | Count |",
            "|-------|-------|",
        ])
        for label, count in labels_accepted.most_common(15):
            lines.append(f"| {label} | {count} |")
        lines.append("")

    # Top labels rejected
    if labels_rejected:
        lines.extend([
            "## Top Labels — Rejected",
            "",
            "| Label | Count |",
            "|-------|-------|",
        ])
        for label, count in labels_rejected.most_common(15):
            lines.append(f"| {label} | {count} |")
        lines.append("")

    # Top reject reasons
    if reason_counter:
        lines.extend([
            "## Top Rejection Reasons",
            "",
            "| Reason | Count |",
            "|--------|-------|",
        ])
        for reason, count in reason_counter.most_common(10):
            lines.append(f"| {reason} | {count} |")
        lines.append("")

    # Output paths
    lines.extend([
        "## Output Paths",
        "",
        f"- Graphs: `{stats.get('output_dir', '')}/graphs/graphs.jsonl`",
        f"- Quality: `{stats.get('output_dir', '')}/quality.jsonl`",
        f"- Overlays: `{stats.get('output_dir', '')}/overlays/`",
        f"- Accepted: `{stats.get('output_dir', '')}/accepted/`",
        f"- Rejected: `{stats.get('output_dir', '')}/rejected/`",
        "",
    ])

    # Claim
    lines.extend([
        "## Ownership Claim",
        "",
        "> Object identification is external/open-vocabulary; skeleton mapping is HyperBone-owned.",
        "",
        "> HyperBone uses open-vocabulary object detection for candidate labeling and bounding boxes, ",
        "> but the structural skeleton graph is generated by a custom HyperBone mapper using owned ",
        "> crop processing, mask approximation, thinning, graph extraction, repair, and quality scoring.",
        "",
    ])

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return path
